from pathlib import Path
import pandas as pd
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer
)
from reportlab.lib.styles import getSampleStyleSheet


PROCESSED_PATH = Path("data/processed")
REPORTS_PATH = Path("reports/generated")

REPORTS_PATH.mkdir(
    parents=True,
    exist_ok=True
)


def clean_filename(text):

    text = str(text)

    replacements = {
        "/": "_",
        "\\": "_",
        "\n": " ",
        "\r": " ",
        ":": "_",
        "*": "_",
        "?": "_",
        "\"": "_",
        "<": "_",
        ">": "_",
        "|": "_"
    }

    for old, new in replacements.items():
        text = text.replace(old, new)

    return text.strip()


def generate_company_reports():

    df = pd.read_csv(
        PROCESSED_PATH / "kpi_master.csv"
    )

    styles = getSampleStyleSheet()

    companies = (
        df["company_name"]
        .dropna()
        .unique()
    )

    generated = 0

    for company in companies:

        company_df = df[
            df["company_name"] == company
        ].copy()

        if len(company_df) == 0:
            continue

        latest = (
            company_df
            .sort_values("year")
            .iloc[-1]
        )

        safe_name = clean_filename(company)

        pdf_file = (
            REPORTS_PATH /
            f"{safe_name}.pdf"
        )

        doc = SimpleDocTemplate(
            str(pdf_file)
        )

        content = []

        content.append(
            Paragraph(
                clean_filename(company),
                styles["Title"]
            )
        )

        content.append(
            Spacer(1, 12)
        )

        fields = [
            ("Sector", latest.get("broad_sector")),
            ("Sub Sector", latest.get("sub_sector")),
            ("Health Score", latest.get("health_score")),
            ("Health Band", latest.get("health_band")),
            ("ROE", latest.get("return_on_equity_pct_final")),
            ("Debt To Equity", latest.get("debt_to_equity_final")),
            ("Free Cash Flow", latest.get("free_cash_flow_cr_final")),
            ("PE Ratio", latest.get("pe_ratio_final")),
            ("PB Ratio", latest.get("pb_ratio_final"))
        ]

        for label, value in fields:

            content.append(
                Paragraph(
                    f"{label}: {value}",
                    styles["Normal"]
                )
            )

        content.append(
            Spacer(1, 20)
        )

        content.append(
            Paragraph(
                "Generated by N100 Financial Intelligence Platform",
                styles["Italic"]
            )
        )

        doc.build(content)

        generated += 1

    print(f"{generated} company reports generated.")


def generate_sector_reports():

    sector_file = (
        PROCESSED_PATH /
        "sector_summary.csv"
    )

    if not sector_file.exists():

        print(
            "sector_summary.csv not found."
        )

        return

    sectors = pd.read_csv(
        sector_file
    )

    styles = getSampleStyleSheet()

    generated = 0

    for _, row in sectors.iterrows():

        sector = clean_filename(
            row["broad_sector"]
        )

        pdf_file = (
            REPORTS_PATH /
            f"Sector_{sector}.pdf"
        )

        doc = SimpleDocTemplate(
            str(pdf_file)
        )

        content = []

        content.append(
            Paragraph(
                sector,
                styles["Title"]
            )
        )

        content.append(
            Spacer(1, 12)
        )

        for col in sectors.columns:

            content.append(
                Paragraph(
                    f"{col}: {row[col]}",
                    styles["Normal"]
                )
            )

        doc.build(content)

        generated += 1

    print(f"{generated} sector reports generated.")


def generate_reports():

    generate_company_reports()

    generate_sector_reports()

    print()
    print("PDF Reporting Completed.")


if __name__ == "__main__":
    generate_reports()